backend:
  image: ghcr.io/workaround-org/presentnow-backend:dev-31
  replicas: 2
  resources:
    limits:
      cpu: "100m"
      memory: "50Mi"
  env:
    QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://unstable-postgres-rw:5432/presentnow"

frontend:
  image:  ghcr.io/workaround-org/presentnow-frontend:dev-23
  replicas: 2
  resources:
    limits:
      cpu: "50m"
      memory: "10Mi"

ingress:
  hosts:
    - ideas.ha1nz.de
    - presentnow.u-project.de
  tlsSecret: presentnow-tls
  issuer: letsencrypt-prod
