backend:
  image: ghcr.io/workaround-org/presentnow-backend:dev-38
  replicas: 2
  database:
    secretName: presentnow-postgres-app
    jdbcUrlSecretKey: jdbc-uri
  searchEngine: "https://www.google.com/search?q="
  oidc:
    audience: ""
    authServerUrl: ""
    clientId: ""
  extraEnv: []
  env:
    QUARKUS_DATASOURCE_JDBC_URL: ""
  resources:
    limits:
      cpu: "100m"
      memory: "50Mi"

frontend:
  image:  ghcr.io/workaround-org/presentnow-frontend:dev-41
  replicas: 2
  resources:
    limits:
      cpu: "50m"
      memory: "10Mi"

ingress:
  hosts:
    - presentnow.example.com
  tlsSecret: presentnow-tls
  issuer: letsencrypt-prod
