apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "present-now.fullname" . }}-gui
  labels:
    app: {{ include "present-now.fullname" . }}-gui
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "present-now.fullname" . }}-gui
  template:
    metadata:
      labels:
        app: {{ include "present-now.fullname" . }}-gui
    spec:
      containers:
        - name: gui
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: presentnow-gui-service
spec:
  selector:
    app: {{ include "present-now.fullname" . }}-gui
  ports:
    - port: 80
      targetPort: 80