apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "present-now.fullname" . }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer | quote }}
spec:
  tls:
  - hosts:
    {{- range .Values.ingress.hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .Values.ingress.tlsSecret }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
        - path: /api/
          pathType: Prefix
          backend:
            service:
              name: presentnow-api-service
              port:
                number: 8080
        - path: /
          pathType: Prefix
          backend:
            service:
              name: presentnow-gui-service
              port:
                number: 80
  {{- end }}