name: Deploy Helm Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_SECRET }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to presentnow-dev
        run: |
          helm upgrade present-now . -n presentnow-dev --install --wait

      - name: Deploy to presentnow-miggi
        run: |
          helm upgrade present-now . -n presentnow-miggi -f values-miggi.yaml --install --wait
